from building import *
Import('rtconfig')

src   = []
cwd   = GetCurrentDir()
group = []
CPPPATH = []

# add network samples.
if GetDepend('RT_USING_SAMPLE_TCP_CLIENT'):
    src += ['tcpclient/tcpclient.c']
    CPPPATH += [cwd + '/tcpclient']

if GetDepend('RT_USING_SAMPLE_TCP_SERVER'):
    src += ['tcpserver/tcpserver.c']
    CPPPATH += [cwd + '/tcpserver']

if GetDepend('RT_USING_SAMPLE_UDP_CLIENT'):
    src += ['udpclient/udpclient.c']
    CPPPATH += [cwd + '/udpclient']

if GetDepend('RT_USING_SAMPLE_UDP_SERVER'):
    src += ['udpserver/udpserver.c']
    CPPPATH += [cwd + '/udpserver']
    
if GetDepend('RT_USING_SAMPLE_TCP_CLIENT_SELECT'):
    src += ['tcpclient_select/tcpclient_select.c']
    CPPPATH += [cwd + '/tcpclient_select']

group = DefineGroup('samples', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
