from building import *
Import('rtconfig')

src   = []
cwd   = GetCurrentDir()
group = []
CPPPATH = []

# add Ethernet drvers.
if GetDepend('PKG_USING_SAMPLE_THREAD_CREAT'):
    src += ['thread_create/thread_create.c']
    CPPPATH += [cwd + '/thread_create']

group = DefineGroup('Samples', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
