from building import *
Import('rtconfig')

src   = []
cwd   = GetCurrentDir()
group = []
CPPPATH = []

# add kernel samples.
if GetDepend('RT_USING_SAMPLE_LED'):
    src += ['led/led.c']
    CPPPATH += [cwd + '/led']

group = DefineGroup('samples', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
